export const siteMetadata = {
  title: "EasyCode Recipes",
  author: "Defne Eroğlu",
  avatar: "/media/avatar.jpg",
  occupation: "Software Engineer",
  headerTitle: "Home",
  description: "Recipes for healthy web development skills🤓",
  language: "en-us",
  siteUrl: "https://defneroglu.app",
  siteLogo: "/media/logo.jpg",
  socialBanner: "/media/avatar.jpg",
  email: "edefne878@gmail.com",
  github: "https://github.com/definite2",
  twitter: "https://twitter.com/defne_erogluu",
  linkedin: "https://www.linkedin.com/in/defne-eroglu/",
  locale: "en-US",
};
