export const siteMetadata = {
  title: "DevMuscle",
  author: "Defne Eroğlu",
  avatar: "/media/avatar.jpg",
  occupation: "Software Engineer",
  headerTitle: "Home",
  description: "Train regularly to build muscle and become healthier person🙃... I mean, learn best practices and fundemantals of web development reguarly and become a better developer.",
  language: "en-us",
  siteUrl: "https://defneeroglu.vercel.app",
  siteLogo: "/media/logo.jpg",
  socialBanner: "/media/avatar.jpg",
  email: "edefne878@gmail.com",
  github: "https://github.com/definite2",
  twitter: "https://twitter.com/defne_erogluu",
  linkedin: "https://www.linkedin.com/in/defne-eroglu/",
  locale: "en-US",
  analytics: {
    googleAnalyticsId: "",
  },
};
