export const siteMetadata = {
  title: "DevMuscle",
  author: "Defne Eroğlu",
  avatar: "/media/avatar.jpg",
  occupation: "Software Engineer",
  headerTitle: "Home",
  description: "Practice regularly fundemantals of web development and become stronger 💪, I mean experienced 🤓, software engineer.",
  language: "en-us",
  siteUrl: "https://devmuscle.com",
  siteLogo: "/media/logo.jpg",
  socialBanner: "/media/avatar.jpg",
  email: "edefne878@gmail.com",
  github: "https://github.com/definite2",
  twitter: "https://twitter.com/defne_erogluu",
  linkedin: "https://www.linkedin.com/in/defne-eroglu/",
  locale: "en-US",
  analytics: {
    googleAnalyticsId: "",
  },
};
